### ISSUE TITLE
Bad UTF-8 "To" header encoding?

### ISSUE THREAD

**Issue by andresmrm** [anymail/django-anymail#369] opened 2024-04-12 19:46 UTC
Hi!

I'm getting errors when trying to send messages when the "to" header has non-ASCII chars.
The problem seems to happen when all these conditions are true at the same time:
1. the readable name part of the recipient is big (e.g. "A very long and big name for this recipient" <to@example.com>)
2. there is at least one non-ASCII char
3. there is at least one "special char" (only seems to happen with comma or parenthesis)
4. the special char isn't close to or between no-ASCII chars

I will use the [related test](https://github.com/anymail/django-anymail/blob/bf257ec3f2e26fc761b0f020c60c733e9cc92d7b/tests/test_amazon_ses_backend.py#L184-L196) to better explain:

| Description             | Input                                                | Output                                                                                  | Error?  |
|-------------------------|------------------------------------------------------|-----------------------------------------------------------------------------------------|---------|
| Current test            | `"Người nhận" <to@example.com> `                       | `To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1u?= <to@example.com>`                                   | No      |
| Long                    | `"Người nhận a very very long name" <to@example.com>`  | `To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1u?= a very very long name <to@example.com>`             | No      |
| With comma              | `"Người nhận a very very long, name" <to@example.com>` | `To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1u?= a very very long, name <to@example.com> `           | **YES** |
| Comma between non-ASCII | `"Người nhận a very very long, náme" <to@example.com>` | `To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1uIGEgdmVyeSB2ZXJ5IGxvbmcsIG7DoW1l?=\n <to@example.com>` | No      |
| Comma near non-ASCII    | `"Người nhận, name" <to@example.com> `                 | `To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1uLCBuYW1l?= <to@example.com>`                           | No      |

So, if we have a UTF-8 encoded part and a special char, the special char must also be encoded, but currently this is only happening if the special char is close or between non-ASCII chars.

Commenting [this line](https://github.com/anymail/django-anymail/blob/bf257ec3f2e26fc761b0f020c60c733e9cc92d7b/anymail/backends/amazon_ses.py#L183) seems to encode the entire name in these cases, solving the problem. But I don't know if this has other unwanted consequences.

- Anymail version: 10.3
- ESP: Amazon SES
- Versions of Django 5.0.3, requests 2.30.0, python 3.11.8
- Exact error message and/or stack trace

Example traceback:
```
File ~/.local/lib/python3.11/site-packages/anymail/backends/amazon_ses.py:78, in EmailBackend._send(self, message)
     76 def _send(self, message):
     77     if self.client:
---> 78         return super()._send(message)
     79     elif self.fail_silently:
     80         # (Probably missing boto3 credentials in open().)
     81         return False

File ~/.local/lib/python3.11/site-packages/anymail/backends/base.py:147, in AnymailBaseBackend._send(self, message)
    144     return False
    146 payload = self.build_message_payload(message, self.send_defaults)
--> 147 response = self.post_to_esp(payload, message)
    148 message.anymail_status.esp_response = response
    150 recipient_status = self.parse_recipient_status(response, payload, message)

File ~/.local/lib/python3.11/site-packages/anymail/backends/amazon_ses.py:114, in EmailBackend.post_to_esp(self, payload, message)
    110     response = client_send_api(**payload.params)
    111 except BOTO_BASE_ERRORS as err:
    112     # ClientError has a response attr with parsed json error response
    113     # (other errors don't)
--> 114     raise AnymailAPIError(
    115         str(err),
    116         backend=self,
    117         email_message=message,
    118         payload=payload,
    119         response=getattr(err, "response", None),
    120     ) from err
    121 return response

AnymailAPIError: An error occurred (BadRequestException) when calling the SendEmail operation: Local address contains control or whitespace
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the SendEmail operation: Local address contains control or whitespace
```

**Comment by medmunds** [comment] 2024-04-12 23:15
Thanks for the report and the detailed analysis. I'm able to reproduce this and am investigating. [I hope you don't mind, I edited your report to format the input and output columns as code, because GitHub was hiding important characters essential to understanding the problem.]

It looks like you've uncovered a bug in Python's email package, related to incorrectly "folding" address headers that are too long, when using Content-Transfer-Encoding (CTE) 7bit, and if the headers need "encoded words" and also contain "special characters." I haven't been able to locate a Python bug report for this exact problem, but a similar issue with shorter address headers that *didn't* require folding (https://github.com/python/cpython/issues/81663) was fixed in Python 3.8. I'm guessing they missed the folding case.

Anymail's SES backend needs to [use CTE 7bit](https://github.com/anymail/django-anymail/blob/bf257ec3f2e26fc761b0f020c60c733e9cc92d7b/anymail/backends/amazon_ses.py#L183) (the line of code you identified), because Amazon SES doesn't officially support 8bit CTE, and using it can result in mojibake depending on what other SES options are enabled. (See the comments above that code and Anymail issue #115.)

I'll look into workarounds…

* It seems like Amazon has relaxed [their stance on 8bit](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html#send-email-raw-api:~:text=In%20some%20cases,7%2Dbit%20ASCII.) "in some cases," though still recommends 7bit for anything non-ASCII. We could add an Anymail option to choose 8bit CTE (and risk mojibake) or 7bit CTE (and risk broken address headers). 
  Also, I'm not sure how widespread support is for 8bit email. (Gmail handles it fine, but do you have any recipients still using Outlook 2013? Or some ancient enterprise email gateway appliance?)
* Allowing longer lines would solve the problem (no folding needed), but has similar compatibility concerns to using 8bit (or worse).
* If we can come up with a fix for the Python email package, Anymail might be able to include that code and use it to override broken address header serialization. (This would be my preference.)

**Comment by andresmrm** [comment] 2024-04-13 11:01
Thanks for the quick and complete response, and for improving the table
in my post!

I'll adapt the test case so it can be reproduced without Anymail and
report at CPython.

About the workarounds, it seemed hard to fix the issue without monkey
patching, something I would like to avoid since sending email is a
crucial part of my application. So, for now, I was just going to remove
commas and parenthesis from the addresses...

**Comment by medmunds** [comment] 2024-04-13 18:56
Hmm, looking into this some more, I think it's actually a Django bug. And there's a reasonable workaround Anymail could implement.

Python's `email.message.EmailMessage` class handles the header correctly. But I see the bug when using `django.core.mail.EmailMessage`:

```python
import email.message
import email.policy
import django.core.mail

to = '"Người nhận a very very long, name" <to@example.com>'
policy = email.policy.default.clone(cte_type="7bit")

# Python's EmailMessage class doesn't exhibit bug
msg1 = email.message.EmailMessage()
msg1["To"] = to
print(msg1.as_bytes(policy=policy).decode("ascii"))
# To:
#   =?utf-8?b?TmfGsOG7nWkgbmjhuq1uIGEgdmVyeSB2ZXJ5IGxvbmcs?= name <to@example.com>

# Django's EmailMessage class has bug
msg2 = django.core.mail.EmailMessage(to=[to]).message()
msg2.policy = policy
print(msg2.as_bytes().decode("ascii"))
# [... other headers ...]
# To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1u?= a very very long, name <to@example.com>
```

Django's `EmailMessage.message()` builds a Python [legacy compatibility] `email.message.Message` (wrapped as a Django `SafeMIMEText`). I believe the problem starts when `django.core.mail.message.sanitize_address` calls `Header().encode()` without specifying a `maxlinelen` for the header. This results in a single, very long encoded word for the entire display name. Python tries to refold it while serializing the message, but bugs in the legacy code introduce the error. (I think.) (So technically, this may be a Python bug, but it's in legacy code that won't be fixed. Also, it's probably related to [django#31784].)

I think Anymail should just stop using Django's `EmailMessage.message()`, and instead build its own modern `email.message.EmailMessage` object directly from the Django `EmailMessage`. There are *a lot* of problems in the old Python `Message` code that were fixed in Python ~3.3-3.5's email revamp. (I also think Django should update to the newer class, too, but that's a different discussion.)

Before switching, we'll need to investigate whether there's anything important in Django's SafeMIME classes we'd be losing or need to copy. I suspect a lot of SafeMIME is there solely to work around bugs and security concerns in Python's legacy Message code—issues that don't apply to Python's modern EmailMessage. But I haven't really looked through that part of Django's mail package in a while.

[django#31784]: https://code.djangoproject.com/ticket/31784
[legacy compatibility]: https://docs.python.org/3/library/email.compat32-message.html#compat32-message

**Comment by medmunds** [comment] 2024-04-15 23:12
> Should I report it both at Python and Django?

I'd report it to Django only. I'm pretty sure the problem only occurs with Python email's legacy `email.message.Message`, which uses a [different folding algorithm](https://docs.python.org/3/library/email.policy.html#email.policy.Compat32.fold) (via `email.policy.compat32`) than modern `email.message.EmailMessage` (`email.policy.default`) uses. 

My understanding is the Compat32 legacy layer is there specifically to replicate Python 2's email behavior (including any bugs), so there's not much point in reporting bugs against it.

**Comment by andresmrm** [comment] 2024-04-16 14:51
Done! Feel free to add more info [there](https://code.djangoproject.com/ticket/35378).

**Comment by medmunds** [comment] 2024-06-22 23:43
I've taken another look at this, and now come to the conclusion that it *is* actually an Anymail bug. And the fix you originally identified is correct. (I'm adding some extra tests to make sure.)

Here's what my [example above](https://github.com/anymail/django-anymail/issues/369#issuecomment-2053731851) (and Anymail) is doing wrong:

```python
import email.policy
import django.core.mail

to = '"Người nhận a very very long, name" <to@example.com>'
mime_message = django.core.mail.EmailMessage(to=[to]).message()
print(mime_message.policy)
# Compat32()

mime_message.policy = email.policy.default.clone(cte_type="7bit")  # <-- BUG!
```

Django's `.message()` returns a legacy Python email.message.Message object, and trying to overwrite its legacy Compat32 `policy` with a modern one causes an unholy mix of new and old header encoding code that wasn't intended to work together.

That [attempt to override policy](https://github.com/anymail/django-anymail/blob/v10.3/anymail/backends/amazon_ses.py#L183) is unnecessary in Anymail's Amazon SES backend, because Anymail has already [reencoded all parts as 7bit](https://github.com/anymail/django-anymail/blob/v10.3/anymail/backends/amazon_ses.py#L174-L181), so the only thing left to worry about are the root message headers. And they should already be 7bit clean. So—as you originally noted—removing the line that sets policy will fix this.

Sorry for my confusion. Fix follows.

-----
[More details, and leaving some notes for the future…]

Incidentally, I also tried using a generator-time policy override, which [seems to be a documented approach](https://docs.python.org/3/library/email.policy.html#module-email.policy:~:text=you%20can%20also%20pass%20a%20specific%20policy%20to%20the%20generator%20that%20will%20override%20the%20one%20stored%20on%20the%20message%20object). Unfortunately, it still exhibits the bug—probably because it's still mixing legacy and modern email header code under the hood:

```python
import email.generator
import email.policy
import io
import django.core.mail

to = '"Người nhận a very very long, name" <to@example.com>'
mime_message = django.core.mail.EmailMessage(to=[to]).message()

fp = io.BytesIO()
g = email.generator.BytesGenerator(
    fp, 
    policy=email.policy.default.clone(cte_type="7bit"),
)
g.flatten(mime_message)
print(fp.getvalue().decode("ascii"))
# [... other headers ...]
# To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1u?= a very very long, name <to@example.com>
```

This probably *should be* considered a bug in the Python email package, though I suspect the appropriate fix might be to raise an error about trying to mix incompatible header registries (or something like that).

Finally, if you change that last example to use a 7bit Compat32 policy, it does solve *this* problem—but runs into other issues if you have (e.g.,) non-ASCII content in the message body:

```python
...
g = email.generator.BytesGenerator(
    fp, 
    policy=mime_message.policy.clone(cte_type="7bit"),  # Compat32
)
...
# To: =?utf-8?b?TmfGsOG7nWkgbmjhuq1uIGEgdmVyeSB2ZXJ5IGxvbmcsIG5hbWU=?=
#  <to@example.com>
```

**Closed** 2024-06-23 00:34 UTC
Labels: bug, esp:Amazon SES
