### ISSUE TITLE
how to apply conditional rendering based on recipient variables

### ISSUE THREAD

**Issue by Thamaraiselvan5960** [anymail/django-anymail#296] opened 2022-12-26 07:07 UTC
Reporting an error? It's helpful to know:

* Anymail version - 8.2
* ESP (Mailgun, SendGrid, etc.)
* Your ANYMAIL settings (change secrets to "redacted")
* Versions of Django, requests, python
* django -3.0.2
* python - 3.9
* Exact error message and/or stack trace
* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)

**Comment by medmunds** [comment] 2022-12-27 21:58
@Thamaraiselvan5960 sorry, I'm not sure what you're trying to do here. Did you mean to include a bug report with this?

If you have a question, it might help to check the suggestions at https://anymail.dev/help/

**Comment by Thamaraiselvan5960** [comment] 2022-12-29 10:46
`<a href="{{ INSTANCE.url }}?email_access_code=%recipient.email_access_code%" target="_blank"> `
`<button>View</button> `
`</a>`
all i need is if email_access_code is empty then i don't want the email_access_code in href attribute.

Is this feature available in anymail ?

**Comment by medmunds** [comment] 2022-12-29 23:24
Closing as duplicate of discussion #297

**Closed by medmunds** 2022-12-29 23:24 UTC
