### ISSUE TITLE
HandleBars not working 

### ISSUE THREAD

**Issue by mcroni** [anymail/django-anymail#171] opened 2019-10-30 16:14 UTC
Reporting an error? It's helpful to know:

* Anymail version: django-anymail==7.0.0
* ESP: Mailgun
*  Django==2.0.4, Python 3.6
* Exact error message and/or stack trace
* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)

Anymail used to work with my settings and mailgun, but now the variables i want to replace in my templates dont get replaced i only get this in my emails %recipient.name% . Even used the code below as a test 
```
from django.core.mail import EmailMessage

message = EmailMessage(
    subject=None,  # use the subject in our stored template
    from_email="marketing@example.com",
    to=["Wile E. <wile@example.com>", "rr@example.com"])
message.template_id = "after_sale_followup_offer"  # use this ESP stored template
message.merge_data = {  # per-recipient data to merge into the template
    'wile@example.com': {'NAME': "Wile E.",
                         'OFFER': "15% off anvils"},
    'rr@example.com':   {'NAME': "Mr. Runner"},
}
message.merge_global_data = {  # merge data for all recipients
    'PARTNER': "Acme, Inc.",
    'OFFER': "5% off any Acme product",  # a default if OFFER missing for recipient
}
message.send()
```

**Comment by mcroni** [comment] 2019-10-30 22:20
Thanks for this, i did a thorough review of the various emails i sent, and i realize the emails that are related to my domain, ex `joey@raexxx.com` are the ones which have the `%recipient.name%` showing but the ones from different domains like `jj@gmail.com` or `bb@outlook.com` work perfectly.

**Comment by medmunds** [comment] 2019-10-31 00:20
Sorry, I'm still not understanding the issue you're seeing (and can't reproduce it).

Are you saying that when you send a template message with `from_email='someone@raexxx.com'` and `to=['joey@raexxx.com']` (both from and to your authorized Mailgun sending domain raexxx.com), the template substitutions don't work, but if you repeat the *exact same send* with a `to` address in some other domain (using the same template, from_email, etc.) the substitutions *do* work? If so, that's very weird and unexpected.

Could you share the exact code you're using to construct and send the messages? And the contents of your template (from Mailgun's template editor)?

**Comment by mcroni** [comment] 2019-10-31 02:19
Yes, thats the problem i'm currently facing. 
```
@app.task(default_retry_delay=2 * 60,ignore_result=True)
def shoot_onboarding(company,receivers,details,url):
    data = {}
    for i in details:
        data[i['email']] = {"NAME": str(i['name']).capitalize(),"LINK": url}
    message = EmailMessage(
        from_email="payroll@raexxx.com",
        subject="Welcome",
        to=receivers
    )
    message.template_id = 'onboard-invitation'  # name of template in our account
    message.merge_global_data = {
        'COMPANY': company  # Anymail maps globals to all recipients
    }
    message.merge_data = data
    message.send()
```
and sample template i picked up from mailgun

```
<!DOCTYPE html>
<html style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Actionable emails e.g. reset password</title>


<style type="text/css">
img {
max-width: 100%;
}
body {
-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em;
}
body {
background-color: #f6f6f6;
}
@media only screen and (max-width: 640px) {
  body {
    padding: 0 !important;
  }
  h1 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h2 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h3 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h4 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h1 {
    font-size: 22px !important;
  }
  h2 {
    font-size: 18px !important;
  }
  h3 {
    font-size: 16px !important;
  }
  .container {
    padding: 0 !important; width: 100% !important;
  }
  .content {
    padding: 0 !important;
  }
  .content-wrap {
    padding: 10px !important;
  }
  .invoice {
    width: 100% !important;
  }
}
</style>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">

<table class="body-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
    <td class="container" width="600" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top">
      <div class="content" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
        <table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope itemtype="http://schema.org/ConfirmAction" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;" valign="top">
              <meta itemprop="name" content="Confirm Email" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    Please confirm your email address by clicking the link below. {{NAME}}
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    We may need to send you critical information {{COMPANY}} about our service and it is important that we have an accurate email address.
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" itemprop="handler" itemscope itemtype="http://schema.org/HttpActionHandler" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    <a href="{{URL}}" class="btn-primary" itemprop="url" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; color: #FFF; text-decoration: none; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; background-color: #348eda; margin: 0; border-color: #348eda; border-style: solid; border-width: 10px 20px;">Confirm email address</a>
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    &mdash; The Mailgunners
                  </td>
                </tr></table></td>
          </tr></table><div class="footer" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">
          <table width="100%" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="aligncenter content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; color: #999; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top">Follow <a href="http://twitter.com/mail_gun" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;">@Mail_Gun</a> on Twitter.</td>
            </tr></table></div></div>
    </td>
    <td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
  </tr></table></body>
</html>```

**Comment by medmunds** [comment] 2019-10-31 17:55
OK, I think I see the problem. I'm guessing that your `receivers` list has some email addresses that are not included in your `details` list. When Mailgun builds the message for one of those emails, there's no merge data available, so you see the raw %recipient.VAR% value instead.

As a reminder, when you set Anymail's `merge_data`, it asks Mailgun to perform a "[batch send]" where a separate message is built and sent for each recipient in the `to` list. The `merge_data` needs to include all template variables for every `to` email (or have default values in `merge_global_data`). If any `to` emails are missing from `merge_data`, the results are generally not what you want (and vary by ESP).

Depending on what you're trying to achieve with your `details` and `receivers` lists, there are a few ways to fix this:
* If `details` is the list of the "real" recipients, and `receivers` is other people who should get copied on every message, don't set `to=receivers`. Instead, set `cc=receivers`, and set `to=[i['email'] for i in details]` so that `to` matches the list of real recipients.
* Or if `receivers` is the list of the "real" recipients, you'd need to look at your code that generates `details` and `receivers` and figure out why `details` is sometimes missing data for some of the `receivers`.
* Either way, if there are reasonable defaults for NAME and LINK, you could set them in `merge_global_data`.

(One other minor issue: your template uses `{{URL}}`, but your code sets merge data for `"LINK"`.)

[batch send]: https://anymail.readthedocs.io/en/stable/sending/templates/#batch-sending-with-merge-data

**Comment by medmunds** [comment] 2019-11-08 00:34
@mcroni I'm going to assume you solved your problem and close this, but if my suggestions above didn't help please feel free to re-open with additional details.

**Closed by medmunds** 2019-11-08 00:34 UTC
Labels: esp:Mailgun

**Comment by mcroni** [comment] 2019-11-08 00:41
sorry for the bad manners, but the problem still persists if i send emails to the same domain. Still figuring out the issue, will open it back as suggested if something pops up. Thank you

**Comment by medmunds** [comment] 2019-11-08 02:19
@mcroni no worries. Here's a debugging tip that might help—add this just above your `message.send()`:

```python
    # ...
    missing = set(message.to) - set(message.merge_data.keys())
    if len(missing):
        raise ValueError(f"Uh-oh, missing merge_data for {missing!r}")
    message.send()
```

That'll throw an error with the list of `message.to` recipients who don't have `merge_data` and will end up with %recipient.VAR% in their messages. (You could change `raise ValueError` to `print(...)` or `logger.warn(...)` or whatever works best for getting you debug info.) 

Of course, you'll still need to track down *why* they're missing, but that's occurring somewhere outside the code you posted here.
