### ISSUE TITLE
Missing or invalid basic auth in Anymail Amazon SES webhook

### ISSUE THREAD

**Issue by zehawki** [anymail/django-anymail#194] opened 2020-07-28 20:09 UTC
Hi,

Thanks for the package and the impossibly amazing documentation. 

I'm facing an issue with SES, where I get "Missing or invalid basic auth in Anymail Amazon SES webhook" when doing the subscriber confirmation step.

I'm following exactly the steps in the documentation. Note that basic mail sending via Anymail is just fine.

Anymail version: latest = 7.2
ESP: SES
Django: 2.2.11, requests: 2.23.0, python: 3.5
Exact error message: Missing or invalid basic auth in Anymail Amazon SES webhook
Using https with a x:y WEBHOOK_SECRET

2 setups as follows, both with the same issue.

1. localhost with dev server exposed via ngrok. 
2. localhost with nginx + uwsgi, exposed via ngrok

The ngrok dashboard shows that the SNS request comes in as follows:

Accept-Encoding	gzip,deflate
Authorization	Basic ZmZHRXZ5dUlKMElNWFd1WjoqKioq
Content-Length	1596
Content-Type	text/plain; charset=UTF-8
Host	d5a7b6130b7d.ngrok.io
User-Agent	Amazon Simple Notification Service Agent
X-Amz-Sns-Message-Id	f6cf73d2-25ae-4942-8407-16f1f7925bcd
X-Amz-Sns-Message-Type	SubscriptionConfirmation
X-Amz-Sns-Topic-Arn	<>
X-Forwarded-For	<>
X-Forwarded-Proto	https

Which gets a 401 with

Www-Authenticate	Basic realm="Anymail WEBHOOK_SECRET"

This is the same as #69 but I dont see a solution there....

(Forgot to mention that `print(request.META.get('HTTP_AUTHORIZATION'))` for a POST via Postman is working fine, just to keep Anymail out of the loop)

Few hours of trying stuff and I'm still stuck at this basic point. Any clues would be very appreciated. Thank you.

**Comment by zehawki** [comment] 2020-07-28 21:05
Here's some debugging info, which BTW is showing that the problem is not with Anymail I suppose.

Server is dev localhost, without nginx / uwsgi, just ngrok tunneled.

I am calling a new endpoint via Postman which is of the form https://X:Y@8189963334d9.ngrok.io/api/v1/misc -> this prints the HTTP_AUTHORIZATION field.

Next I gave the same endpoint to SNS for testing and this time, the HTTP_AUTHORIZATION field is not there!

I really dont understand who is stripping away the HTTP_AUTHORIZATION  field.

**Comment by zehawki** [comment] 2020-07-28 22:13
Ok I seemed to have made a bit of progress. I tried with just a simple https://a:b@<>.ngrok.io/anymail/amazon_ses/tracking/ and this time I saw a 401 followed by a 500 which was just a permission problem:

botocore.errorfactory.AuthorizationErrorException: An error occurred (AuthorizationError) when calling the ConfirmSubscription operation: User: <> is not authorized to perform: SNS:ConfirmSubscription on resource: <>

**After adding the SNS permission to the IAM user, I am back to the original error!**

401 followed by 400 error: Missing or invalid basic auth in Anymail Amazon SES webhook

The request from AWS does have the auth:

Accept-Encoding	gzip,deflate
Authorization	Basic YToqKioq
Content-Length	1596
Content-Type	text/plain; charset=UTF-8
Host	8189963334d9.ngrok.io
User-Agent	Amazon Simple Notification Service Agent
X-Amz-Sns-Message-Id	6c27e6b2-c1c9-4ef8-bffa-dac164ff7e22
X-Amz-Sns-Message-Type	SubscriptionConfirmation
X-Amz-Sns-Topic-Arn	<>
X-Forwarded-For	<>
X-Forwarded-Proto	https

**Comment by medmunds** [comment] 2020-07-28 23:40
Sounds like you're making progress, and you're looking at all the things I would.

Just to double check, does the Anymail WEBHOOK_SECRET setting in your settings.py definitely match the exact basic auth you pasted into SNS or Postman? Both of the Authorization headers you posted have `****` as the password portion (literally four asterisk characters—I have not not sanitized this).

That is:
```http
Authorization: Basic YToqKioq
```
[decodes](https://www.base64decode.org/) to match this setting:
```python
ANYMAIL = {
    "WEBHOOK_SECRET": "a:****",  # this is *not* sanitized
}
```

If your settings.py reads `"a:b"` and not `"a:****"`, that's why it's failing. Then the next question will be what is converting your basic auth password to four asterisks, but that will be in Postman or in the SNS dashboard, not Anymail.

(BTW, there's a complete list of [required IAM permissions](https://anymail.readthedocs.io/en/stable/esps/amazon_ses/#amazon-ses-iam-permissions) later in the Anymail docs, in case you haven't found that yet. Amazon SES is definitely the most complicated ESP to get configured properly, and having been there myself, I feel your pain.)

**Comment by zehawki** [comment] 2020-07-28 23:45
There is light at the end of this tunnel. Bwahaha.

I brought in your code and added prints to see what exactly was happening here:

```
            auth_ok = any(constant_time_compare(request_auth, allowed_auth)
                          for allowed_auth in self.basic_auth)
```

Thats when I figured out that AWS was sending Authorization = "Basic YToqKioq" which actually decodes to "a:****".

So I set up another subscription with the same _https://a:b@<>.ngrok.io/anymail/amazon_ses/tracking/_ and this time Auth came with "Basic YTpi" which is correctly "a:b" and the subscription got confirmed as expected.

-------

Well, so here's the source of this annoying problem: When there is a failure the first time a subscription is created, from the subsequent times, AWS actually sends the password as "****". I.e clicking the "request confirmation" button keeps sending the password as ****.

To confirm this I decoded the auth string from my 1st message above which was _Authorization Basic ZmZHRXZ5dUlKMElNWFd1WjoqKioq_, and it turns out to be "ffGEvyuIJ0IMXWuZ:****"

Ahhhhhhhhhhhhhhhhhh.

**Comment by medmunds** [comment] 2020-07-28 23:51
Nice work! Glad you found it.

And, yikes!, that's some seriously misleading (buggy) behavior in the AWS dashboard. You might want to report it to them—I can't imagine you're the first person who has run into this, but you might be the first who figured out the cause and can let them know.

**Comment by zehawki** [comment] 2020-07-29 00:06
Yup, I'll go ahead and report it to them... whew thats been an all nighter on my side. Cheers. Thanks for the super quick responses!

> there's a complete list of required IAM permissions later in the Anymail docs

Yup that was a life saver, I used that to solve the SNS permission issue I faced.

PS: I'm just blown away by the documentation that you have here. So super helpful. I've read thru all the pages and even sent a comment about track_opens and track_clicks.
Unlike [this](https://github.com/stripe/react-stripe-elements/issues/451) :-)

**Comment by zehawki** [comment] 2020-07-29 08:51
Sorry to open this again, but though it might be easier this way. I just stumbled upon this https://maxbeatty.com/2015/11/16/how-to-subscribe-to-aws-sns-using-https-with-basic-authentication/ from 2015. Its been 5 years and AWS hasnt bothered to fix it, so chances are they cant be bothered. Would you please add a note in your docs to help the next guy who runs into this headache.

**Comment by medmunds** [comment] 2020-07-29 19:17
Yeah, I'll update the docs, especially the part where they suggest just re-sending the confirmation request if necessary.

I'm not sure AWS engineering monitors maxbeatty.com, but they do pay some attention to the AWS Forums. I found a few mentions of this issue there, but none that included the key step to reproduce the problem: using the "Request confirmation" button to re-send the request. I updated [one of the recent ones](https://forums.aws.amazon.com/thread.jspa?messageID=950832&#950832) with this detail; we'll see what happens.

And yes, SNS doesn't send the Authorization header until after the server specifically requests it with a 401 Unauthorized response (Anymail will handle that for you). That's because SNS actually supports a couple variants of HTTP auth, and doesn't know which one to use until the server specifies it in the 401 response. (Their docs do mention this, though they assume a lot of familiarity with HTTP auth. See the blue box and the RFC link under "[Basic and Digest Access Authentication](https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html)".)

**Closed** 2020-07-29 21:42 UTC
Labels: docs, esp:Amazon SES
