### ISSUE TITLE
SES backend not sending email to bcc

### ISSUE THREAD

**Issue by anuj9196** [anymail/django-anymail#199] opened 2020-08-06 09:15 UTC
Reporting an error? It's helpful to know:

* Anymail version: **django-anymail==7.1.0**
* ESP (Mailgun, SendGrid, etc.): **SES**
* Your ANYMAIL settings (change secrets to "redacted")
```
EMAIL_BACKEND = "anymail.backends.amazon_ses.EmailBackend"
ANYMAIL = {
    'AMAZON_SES_MESSAGE_TAG_NAME': 'Type',
    'WEBHOOK_SECRET': os.environ.get('ANYMAIL_WEBHOOK_SECRET', '')
}
```
* Versions of Django, requests, python: **Django 2.2**
* Exact error message and/or stack trace
Emails are not received on the BCC address

* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)
```
msg = EmailMultiAlternatives(
            subject=subject,
            body=body_text,
            from_email='{} <{}>'.format(from_email_name, from_email),
            to=[to],
            cc=[cc],
            bcc=[bcc]
        )

        msg.esp_extra = {
            'Tags': [
                {'Name': 'App', 'Value': '{}'.format(self.app_name).replace(' ', '_')}
            ]
        }

        if attachments and type(attachments) == list:
            msg.attachments = attachments

        if body_html:
            msg.attach_alternative(body_html, 'text/html')

        self.last_send_status = msg.send()
        log.info('Email sent')
```

**Comment by medmunds** [comment] 2020-08-06 15:04
Duplicate of #189

**Closed by medmunds** 2020-08-06 15:04 UTC
Labels: duplicate
